import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const packageRoot = fileURLToPath(new URL('../', import.meta.url));
const tokenFile = resolve(packageRoot, '../../design/generated/vscode-fallback.css');
export const forkStylesheet = 'src/vs/workbench/contrib/obraSidebar/browser/media/obraSidebar.generated.css';

/** Resolve Obra tokens at build time; retain live VS Code theme bindings. */
export function generateStylesheet(source, tokenLayer) {
  const declarations = new Map(
    [...tokenLayer.matchAll(/^\s*(--obra-[\w-]+): (.+);$/gm)].map((match) => [match[1], match[2]])
  );
  const used = [...new Set(source.match(/--obra-[\w-]+/g) ?? [])].sort();
  for (const name of used) {
    const value = declarations.get(name);
    if (value === undefined) throw new Error(`Unknown Obra token: ${name}`);
  }
  // Native stylelint knows --vscode-* variables. Emitting their bindings avoids
  // editing the upstream variable registry for package-private --obra-* aliases.
  const resolvedSource = source.replace(/var\((--obra-[\w-]+)\)/g, (_, name) => declarations.get(name));
  if (/var\(--obra-/.test(resolvedSource)) throw new Error('Obra token references must use var(--obra-token) without a fallback.');
  return [
    '/*---------------------------------------------------------------------------------------------',
    ' *  Copyright (c) Microsoft Corporation. All rights reserved.',
    ' *  Licensed under the MIT License. See License.txt in the project root for license information.',
    ' *--------------------------------------------------------------------------------------------*/',
    '',
    '/* OBRA(PL-015): Generated by @obra/workbench-ui. Do not edit in the fork.',
    ' * Source: ui/packages/obra-workbench-ui/src/sidebar.css; pnpm workbench:sync.',
    ' * Token source: ui/design/generated/vscode-fallback.css.',
    ' */',
    resolvedSource.trim(),
    '',
  ].join('\n');
}

/** Check without writing, or emit a deterministic standalone stylesheet. */
export function emitStylesheet(file, css, check) {
  if (check) {
    if (readFileSync(file, 'utf8') !== css) throw new Error(`Stale stylesheet: ${file}`);
    return;
  }
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, css);
}

function main() {
  const args = process.argv.slice(2);
  let check = false;
  let forkRoot;
  for (let index = 0; index < args.length; index++) {
    if (args[index] === '--check') check = true;
    else if (args[index] === '--vscode-root' && args[index + 1]) forkRoot = resolve(args[++index]);
    else throw new Error(`Unknown or incomplete argument: ${args[index]}`);
  }
  // Validate the host before emitting anything. Never assume a sibling exists.
  if (forkRoot) {
    JSON.parse(readFileSync(resolve(forkRoot, 'product.json'), 'utf8'));
    readFileSync(resolve(forkRoot, 'src/vs/workbench/workbench.common.main.ts'), 'utf8');
  }
  const css = generateStylesheet(
    readFileSync(resolve(packageRoot, 'src/sidebar.css'), 'utf8'),
    readFileSync(tokenFile, 'utf8')
  );
  emitStylesheet(resolve(packageRoot, 'dist/sidebar.css'), css, check);
  if (forkRoot) emitStylesheet(resolve(forkRoot, forkStylesheet), css, check);
  console.log(`[workbench-ui] ${check ? 'Checked' : 'Generated'} sidebar stylesheet${forkRoot ? ' and fork artifact' : ''}.`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) main();
