// Verify the normal built-in packaging path and inspect an actual VSIX archive.
import assert from 'node:assert/strict';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const uiRoot = fileURLToPath(new URL('../../../', import.meta.url));
const fork = resolve(uiRoot, '../vscode');
const require = createRequire(resolve(fork, 'build/package.json'));
const vsce = require('@vscode/vsce');
const glob = require('glob');
const destination = resolve(uiRoot, '.tmp/reports/obra-sidebar');
mkdirSync(destination, { recursive: true });
const manifestPath = 'extensions/obra-workbench-ui/package.json';
assert.ok(glob.sync('extensions/*/package.json', { cwd: fork }).includes(manifestPath));
const build = readFileSync(resolve(fork, 'build/lib/extensions.ts'), 'utf8');
assert.match(build, /glob\.sync\('extensions\/\*\/package\.json'\)/);
assert.match(build, /input = fromLocalNormal\(extensionPath\)/);
const excluded = build.match(/const excludedExtensions = \[([\s\S]*?)\];/)[1];
assert.ok(!excluded.includes('obra-workbench-ui'));
const cwd = resolve(fork, 'extensions/obra-workbench-ui');
const files = await vsce.listFiles({ cwd, packageManager: vsce.PackageManager.Npm });
const vsix = resolve(destination, 'obra-workbench-ui.vsix');
await vsce.createVSIX({ cwd, packagePath: vsix, packageManager: vsce.PackageManager.Npm, allowMissingRepository: true, skipLicense: true });
const archive = execFileSync('unzip', ['-Z1', vsix], { encoding: 'utf8' }).trim().split('\n');
for (const file of files) assert.ok(archive.includes(`extension/${file}`), file);
const report = { status: 'passed', builtInGlob: manifestPath, path: 'packageNonNativeLocalExtensionsStream → fromLocalNormal → vsce.listFiles', files: files.sort(), vsix, archive };
writeFileSync(resolve(destination, 'packaging.json'), JSON.stringify(report, null, 2));
console.log(JSON.stringify(report, null, 2));
