#!/usr/bin/env node
// Builds design/generated/* from design/tokens/*.json (DTCG).
// Zero dependencies on purpose: CI and every package can run it.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const tokenDir = join(root, 'design', 'tokens');
const outDir = join(root, 'design', 'generated');

const FILES = ['primitive.json', 'vscode.json', 'semantic.json', 'component.json'];

/** camelCase / kebab segment -> kebab segment */
function kebab(seg) {
  return seg
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[_\s]+/g, '-')
    .toLowerCase();
}

/** Flatten a DTCG object into { "a.b.c": token } for leaves (nodes with $value). */
function flatten(obj, prefix, out) {
  for (const [key, val] of Object.entries(obj)) {
    if (key.startsWith('$')) continue;
    const path = prefix ? `${prefix}.${key}` : key;
    if (val && typeof val === 'object' && '$value' in val) {
      out.set(path, val);
    } else if (val && typeof val === 'object') {
      flatten(val, path, out);
    }
  }
  return out;
}

const tokens = new Map();
for (const f of FILES) {
  const json = JSON.parse(readFileSync(join(tokenDir, f), 'utf8'));
  flatten(json, '', tokens);
}

const ALIAS = /^\{([^}]+)\}$/;

/** Resolve a token to its literal value (following aliases), detecting vscode bridge. */
function resolve(path, seen = new Set()) {
  if (seen.has(path)) throw new Error(`Circular token alias at ${path}`);
  seen.add(path);
  const tok = tokens.get(path);
  if (!tok) throw new Error(`Unknown token reference {${path}}`);
  const vscodeVar = tok.$extensions?.['obra.vscodeVar'];
  const raw = tok.$value;
  const m = typeof raw === 'string' ? raw.match(ALIAS) : null;
  if (m) {
    const inner = resolve(m[1], seen);
    return inner;
  }
  return { literal: String(raw), vscodeVar: vscodeVar || null, type: tok.$type };
}

const cssName = (path) => '--obra-' + path.split('.').map(kebab).join('-');

const entries = [...tokens.entries()]
  .map(([path]) => ({ path, resolved: resolve(path) }))
  .sort((a, b) => a.path.localeCompare(b.path));

mkdirSync(outDir, { recursive: true });

// 1) tokens.css — resolved literal values (Storybook / harness / no host).
const cssLines = [
  '/* GENERATED by scripts/build-tokens.mjs — do not edit. Source: design/tokens/. */',
  ':root {',
  ...entries.map(({ path, resolved }) => `  ${cssName(path)}: ${resolved.literal};`),
  '}',
  '',
];
writeFileSync(join(outDir, 'tokens.css'), cssLines.join('\n'));

// 2) vscode-fallback.css — runtime layer mapping to real --vscode-* variables.
const fbLines = [
  '/* GENERATED by scripts/build-tokens.mjs — do not edit. */',
  '/* Load inside a VS Code webview: --obra-* resolve to the live theme. */',
  ':root {',
  ...entries.map(({ path, resolved }) =>
    resolved.vscodeVar
      ? `  ${cssName(path)}: var(${resolved.vscodeVar}, ${resolved.literal});`
      : `  ${cssName(path)}: ${resolved.literal};`
  ),
  '}',
  '',
];
writeFileSync(join(outDir, 'vscode-fallback.css'), fbLines.join('\n'));

// 3) tokens.ts — typed token map for @obra/ui.
const tsKeys = entries.map(({ path }) => path);
const tsLines = [
  '// GENERATED by scripts/build-tokens.mjs — do not edit.',
  'export const tokenPaths = [',
  ...tsKeys.map((k) => `  ${JSON.stringify(k)},`),
  '] as const;',
  '',
  'export type TokenPath = (typeof tokenPaths)[number];',
  '',
  'export const cssVar = (path: TokenPath): string =>',
  "  '--obra-' + path.split('.').map((s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()).join('-');",
  '',
  'export const tokens = Object.fromEntries(',
  '  tokenPaths.map((p) => [p, cssVar(p)]),',
  ') as Record<TokenPath, string>;',
  '',
];
writeFileSync(join(outDir, 'tokens.ts'), tsLines.join('\n'));

// 4) penpot-tokens.json — Penpot token import (DTCG-shaped, grouped).
function nest(flatEntries) {
  const out = {};
  for (const { path, resolved } of flatEntries) {
    const segs = path.split('.');
    let node = out;
    for (let i = 0; i < segs.length - 1; i++) {
      node[segs[i]] = node[segs[i]] || {};
      node = node[segs[i]];
    }
    node[segs[segs.length - 1]] = {
      $type: resolved.type,
      $value: resolved.vscodeVar
        ? `var(${resolved.vscodeVar}, ${resolved.literal})`
        : resolved.literal,
    };
  }
  return out;
}
writeFileSync(
  join(outDir, 'penpot-tokens.json'),
  JSON.stringify({ obra: nest(entries) }, null, 2) + '\n'
);

// 5) tokens.md — human documentation.
const md = [
  '# Generated tokens',
  '',
  'Generated by `scripts/build-tokens.mjs` from `design/tokens/`. Do not edit.',
  '',
  `Total tokens: ${entries.length}.`,
  '',
  '| Token | CSS var | VS Code var | Resolved |',
  '|---|---|---|---|',
  ...entries.map(({ path, resolved }) =>
    `| \`${path}\` | \`${cssName(path)}\` | ${resolved.vscodeVar ? `\`${resolved.vscodeVar}\`` : '—'} | \`${resolved.literal}\` |`
  ),
  '',
];
writeFileSync(join(outDir, 'tokens.md'), md.join('\n'));

console.log(`[tokens] wrote ${entries.length} tokens to ${outDir}`);
